// <auto-generated />
using System;
using BeautyPro.CRM.EF.DomainModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeautyPro.CRM.EF.Migrations
{
    [DbContext(typeof(BeautyProContext))]
    partial class BeautyProContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.Branch", b =>
                {
                    b.Property<int>("BranchId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("CompanyId");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Fax")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Tp1")
                        .IsRequired()
                        .HasColumnName("TP1")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Tp2")
                        .HasColumnName("TP2")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Tbl_Branch");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CreditCardType", b =>
                {
                    b.Property<int>("CCTId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CCTId");

                    b.ToTable("Tbl_Mast_CreditCardType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Address")
                        .HasMaxLength(350)
                        .IsUnicode(false);

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LoyaltyCardNo")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Profession")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CustomerId")
                        .HasName("PK_Tbl_Master_Customer");

                    b.HasIndex("BranchId");

                    b.ToTable("Tbl_Customer");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerGiftVoucher", b =>
                {
                    b.Property<string>("GvinvoiceNo")
                        .HasColumnName("GVInvoiceNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("BranchId");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("CanceledBy");

                    b.Property<DateTime?>("CanceledDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("DepartmentId");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("InvDateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsCanceled");

                    b.Property<bool>("IsRedeem");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Ptid")
                        .HasColumnName("PTId");

                    b.Property<decimal>("SubTotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TransType");

                    b.Property<int?>("Ttid")
                        .HasColumnName("TTId");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("GvinvoiceNo");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Ptid");

                    b.HasIndex("Ttid");

                    b.ToTable("Tbl_CustomerGiftVoucher");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerInvoiceHeader", b =>
                {
                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("AmendedReason");

                    b.Property<int>("BranchId");

                    b.Property<int?>("CCTId");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("CanceledBy");

                    b.Property<DateTime?>("CanceledDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("CustomerScheduleTreatmentCstid");

                    b.Property<int>("DepartmentId");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GvinvoiceNo")
                        .HasColumnName("GVInvoiceNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime>("InvDateTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsAmended");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ProductDueAmount");

                    b.Property<decimal>("ProductSubTotalAmount");

                    b.Property<decimal>("ProductTaxAmount");

                    b.Property<int>("Ptid")
                        .HasColumnName("PTId");

                    b.Property<int>("Status");

                    b.Property<string>("TransType")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal>("TreatmentDiscountAmount");

                    b.Property<decimal>("TreatmentDueAmount");

                    b.Property<decimal>("TreatmentSubTotalAmount");

                    b.Property<decimal>("TreatmentTaxAmount");

                    b.HasKey("InvoiceNo");

                    b.HasIndex("CCTId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerScheduleTreatmentCstid");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Ptid");

                    b.ToTable("Tbl_CustomerInvoiceHeader");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerInvoiceProducts", b =>
                {
                    b.Property<int>("Cipid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CIPId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Empno");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Cipid");

                    b.HasIndex("Empno");

                    b.HasIndex("InvoiceNo");

                    b.HasIndex("ProductId");

                    b.ToTable("Tbl_CustomerInvoiceProducts");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerInvoiceTreatment", b =>
                {
                    b.Property<int>("Citid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CITId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Cstid");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Qty");

                    b.Property<int>("Ttid")
                        .HasColumnName("TTId");

                    b.HasKey("Citid");

                    b.HasIndex("Cstid");

                    b.HasIndex("Empno");

                    b.HasIndex("InvoiceNo");

                    b.HasIndex("Ttid");

                    b.ToTable("Tbl_CustomerInvoiceTreatment");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerSchedule", b =>
                {
                    b.Property<int>("Csid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CSId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookedDate")
                        .HasColumnType("date");

                    b.Property<int>("BranchId");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Csid");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tbl_CustomerSchedule");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerScheduleTreatment", b =>
                {
                    b.Property<int>("Cstid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CSTId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Csid")
                        .HasColumnName("CSId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<TimeSpan>("EndTime");

                    b.Property<int>("Qty");

                    b.Property<TimeSpan>("StartTime");

                    b.Property<int>("Ttid")
                        .HasColumnName("TTId");

                    b.HasKey("Cstid");

                    b.HasIndex("Csid");

                    b.HasIndex("Empno");

                    b.HasIndex("Ttid");

                    b.ToTable("Tbl_CustomerScheduleTreatment");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.Department", b =>
                {
                    b.Property<int>("DepartmentId");

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool?>("IsMain");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("DepartmentId");

                    b.HasIndex("BranchId");

                    b.ToTable("Tbl_Mast_Department");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.DiscountType", b =>
                {
                    b.Property<int>("DTId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Discount");

                    b.HasKey("DTId");

                    b.ToTable("Tbl_Mast_DiscountType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", b =>
                {
                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<string>("Address")
                        .HasMaxLength(350);

                    b.Property<string>("BankAccountNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("BankId");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BranchId");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int>("CountryId");

                    b.Property<DateTime>("DateOfJoin")
                        .HasColumnType("date");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId");

                    b.Property<int>("DesignationId");

                    b.Property<DateTime?>("Dob")
                        .HasColumnName("DOB")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("EmergencyContactNo")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("EmergencyContactPerson")
                        .HasMaxLength(100);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Gender")
                        .HasMaxLength(20);

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int?>("NationalityId");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Status")
                        .HasMaxLength(200);

                    b.HasKey("Empno");

                    b.HasIndex("BankId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("NationalityId");

                    b.ToTable("Tbl_EmployeeDetail");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.EmployeeRoster", b =>
                {
                    b.Property<int>("RosterId");

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("InTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("OutTime");

                    b.Property<DateTime>("WorkingDate")
                        .HasColumnType("date");

                    b.HasKey("RosterId")
                        .HasName("PK_Tbl_RosterDetail");

                    b.HasIndex("Empno");

                    b.ToTable("Tbl_EmployeeRoster");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.PaymentType", b =>
                {
                    b.Property<int>("Ptid")
                        .HasColumnName("PTId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Ptname")
                        .IsRequired()
                        .HasColumnName("PTName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Ptid");

                    b.ToTable("Tbl_Mast_PaymentType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.Product", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnName("ItemID")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<int?>("CatId")
                        .HasColumnName("CatID");

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ItemName")
                        .HasMaxLength(100);

                    b.Property<decimal?>("LastPurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("LeadTime")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("MaxQty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinQty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductSellingPriceItemId")
                        .HasColumnType("char(4)");

                    b.Property<decimal?>("ReOrderLevel")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ReOrderQty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UnitId")
                        .HasColumnName("UnitID");

                    b.HasKey("ItemId")
                        .HasName("PK_Items");

                    b.HasIndex("ProductSellingPriceItemId");

                    b.ToTable("Tbl_Product");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.ProductSellingPrice", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnName("ItemID")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ItemId")
                        .HasName("PK_ItemSellingPrice");

                    b.ToTable("Tbl_ProductSellingPrice");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblCompany", b =>
                {
                    b.Property<int>("CompanyId");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(350)
                        .IsUnicode(false);

                    b.HasKey("CompanyId")
                        .HasName("PK_Tbl_Master_Company");

                    b.ToTable("Tbl_Company");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblConfig", b =>
                {
                    b.Property<int>("ConfigId");

                    b.Property<decimal>("AbsentDeductionRatio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PresentAllawancesRatio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ConfigId");

                    b.ToTable("Tbl_Config");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeAllowances", b =>
                {
                    b.Property<int>("Eaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EAId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllowanceId");

                    b.Property<decimal>("AllowanceValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MonthId");

                    b.HasKey("Eaid")
                        .HasName("PK_Tbl_EmployeeAllowances_1");

                    b.HasIndex("AllowanceId");

                    b.HasIndex("Empno");

                    b.ToTable("Tbl_EmployeeAllowances");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeAttendance", b =>
                {
                    b.Property<int>("AttendanceId");

                    b.Property<int>("BranchId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("LateMins")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MonthId");

                    b.Property<decimal>("Ot1")
                        .HasColumnName("OT1")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("OutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("WorkedHrs")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("AttendanceId");

                    b.ToTable("Tbl_EmployeeAttendance");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeBasicSalary", b =>
                {
                    b.Property<int>("Ebsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EBSId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("BasicSalaryValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MonthId");

                    b.HasKey("Ebsid");

                    b.HasIndex("Empno");

                    b.ToTable("Tbl_EmployeeBasicSalary");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeCommision", b =>
                {
                    b.Property<int>("Ecid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ECId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<decimal>("CommisionValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CommissionId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MonthId");

                    b.HasKey("Ecid")
                        .HasName("PK_Tbl_EmployeeCommision_1");

                    b.HasIndex("CommissionId");

                    b.HasIndex("Empno");

                    b.ToTable("Tbl_EmployeeCommision");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeDeduction", b =>
                {
                    b.Property<int>("Edid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EDId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<int>("DeductionId");

                    b.Property<decimal?>("DeductionValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MonthId");

                    b.HasKey("Edid")
                        .HasName("PK_Tbl_EmployeeDeduction_1");

                    b.HasIndex("DeductionId");

                    b.HasIndex("Empno");

                    b.ToTable("Tbl_EmployeeDeduction");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeLeave", b =>
                {
                    b.Property<int>("EmployeeLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsNope");

                    b.Property<int>("LeaveTypeId");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Remark")
                        .HasMaxLength(150);

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime");

                    b.HasKey("EmployeeLeaveId");

                    b.HasIndex("Empno");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("Tbl_EmployeeLeave");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeSalarySupport", b =>
                {
                    b.Property<int>("Essid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ESSid")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<string>("ChequNo")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int>("Empno")
                        .HasColumnName("EMPNo");

                    b.Property<int>("MonthId");

                    b.Property<int>("NoOfPresentDays");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Essid");

                    b.ToTable("Tbl_EmployeeSalarySupport");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastAllowances", b =>
                {
                    b.Property<int>("AllowanceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("AllowanceId")
                        .HasName("PK_Tbl_Mast_SalaryDetail");

                    b.ToTable("Tbl_Mast_Allowances");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastBank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("BankId");

                    b.ToTable("Tbl_Mast_Bank");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastCommission", b =>
                {
                    b.Property<int>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal?>("Ratio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CommissionId")
                        .HasName("PK_Tbl_Mast_CommissionDetail");

                    b.ToTable("Tbl_Mast_Commission");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastDeduction", b =>
                {
                    b.Property<int>("DeductionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<int?>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal?>("Ratio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("DeductionId")
                        .HasName("PK_Tbl_Mast_DeductionDetail");

                    b.ToTable("Tbl_Mast_Deduction");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastDesignation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("DesignationId");

                    b.HasIndex("BranchId");

                    b.ToTable("Tbl_Mast_Designation");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastLeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllowDate");

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("LeaveTypeId");

                    b.ToTable("Tbl_Mast_LeaveType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastNationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(10);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("NationalityId");

                    b.ToTable("Tbl_Mast_Nationality");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastOriginCountry", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("CountryId");

                    b.ToTable("Tbl_Mast_OriginCountry");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastProductCategory", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CatID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<string>("CatName")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.HasKey("CatId")
                        .HasName("PK_Category");

                    b.ToTable("Tbl_Mast_ProductCategory");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastProductUnits", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UnitID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50);

                    b.HasKey("UnitId")
                        .HasName("PK_Units");

                    b.ToTable("Tbl_Mast_ProductUnits");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastSuppliers", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SupplierID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(250);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(100);

                    b.Property<string>("ContactPersonTelNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100);

                    b.HasKey("SupplierId")
                        .HasName("PK_Suppliers");

                    b.ToTable("Tbl_Mast_Suppliers");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMonth", b =>
                {
                    b.Property<int>("MonthId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("EnteredBy");

                    b.Property<DateTime?>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FinMonth")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("FinYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.HasKey("MonthId");

                    b.ToTable("Tbl_Month");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductGindetails", b =>
                {
                    b.Property<string>("Ginno")
                        .HasColumnName("GINNO")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("ItemNo")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("Ginno", "ItemNo")
                        .HasName("PK_GINDetails");

                    b.ToTable("Tbl_ProductGINDetails");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductGinheader", b =>
                {
                    b.Property<string>("Ginno")
                        .HasColumnName("GINNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<DateTime?>("Gindate")
                        .HasColumnName("GINDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDelete");

                    b.Property<int?>("IsDeletedBy");

                    b.Property<string>("Remarks")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId");

                    b.HasKey("Ginno")
                        .HasName("PK_GINHeader");

                    b.ToTable("Tbl_ProductGINHeader");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductGrndetails", b =>
                {
                    b.Property<string>("Grnno")
                        .HasColumnName("GRNNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("ItemId")
                        .HasColumnName("ItemID")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal?>("PriceVarianceValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50);

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UnitId")
                        .HasColumnName("UnitID");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Grnno", "ItemId")
                        .HasName("PK_GRNDetails");

                    b.ToTable("Tbl_ProductGRNDetails");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductGrnheader", b =>
                {
                    b.Property<string>("Grnno")
                        .HasColumnName("GRNNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<DateTime?>("Grndate")
                        .HasColumnName("GRNDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsCach");

                    b.Property<bool?>("IsDelete");

                    b.Property<int?>("IsDeletedBy");

                    b.Property<string>("Pono")
                        .HasColumnName("PONo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Remarks")
                        .HasMaxLength(50);

                    b.Property<int>("SupplierId")
                        .HasColumnName("SupplierID");

                    b.Property<string>("SupplierInvoiceNo")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("SupplierIvoiceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("Grnno")
                        .HasName("PK_GRNHeader");

                    b.ToTable("Tbl_ProductGRNHeader");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductPondetails", b =>
                {
                    b.Property<string>("Pono")
                        .HasColumnName("PONo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("ItemId")
                        .HasColumnName("ItemID")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50);

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UnitId")
                        .HasColumnName("UnitID");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Pono", "ItemId")
                        .HasName("PK_PurchasedOrder_Details");

                    b.ToTable("Tbl_ProductPONDetails");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductPonheader", b =>
                {
                    b.Property<string>("Pono")
                        .HasColumnName("PONo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<bool?>("IsCach");

                    b.Property<bool?>("IsDelete");

                    b.Property<int?>("IsDeletedBy");

                    b.Property<bool?>("IsPurchased")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("Podate")
                        .HasColumnName("PODate")
                        .HasColumnType("datetime");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50);

                    b.Property<int>("SupplierId")
                        .HasColumnName("SupplierID");

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("Pono")
                        .HasName("PK_PurchasedOrder_Header");

                    b.ToTable("Tbl_ProductPONHeader");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductReceptionGrndetail", b =>
                {
                    b.Property<string>("ReceptionGrnno")
                        .HasColumnName("ReceptionGRNNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("ItemId")
                        .HasColumnName("ItemID")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UnitId")
                        .HasColumnName("UnitID");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ReceptionGrnno", "ItemId")
                        .HasName("PK_ReceptionGRNDetail");

                    b.ToTable("Tbl_ProductReceptionGRNDetail");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductReceptionGrnheader", b =>
                {
                    b.Property<string>("ReceptionGrnno")
                        .HasColumnName("ReceptionGRNNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<DateTime>("Grndate")
                        .HasColumnName("GRNDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDelete");

                    b.Property<int?>("IsDeletedBy");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("ReceptionGrnno")
                        .HasName("PK_ReceptionGRNHeader");

                    b.ToTable("Tbl_ProductReceptionGRNHeader");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductSrndetails", b =>
                {
                    b.Property<string>("Srnno")
                        .HasColumnName("SRNNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("ItemId")
                        .HasColumnName("ItemID")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal?>("Qry")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50);

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UnitId")
                        .HasColumnName("UnitID");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Srnno", "ItemId")
                        .HasName("PK_SRNDetails");

                    b.ToTable("Tbl_ProductSRNDetails");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblProductSrnheader", b =>
                {
                    b.Property<string>("Srnno")
                        .HasColumnName("SRNNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchID");

                    b.Property<string>("Grnno")
                        .HasColumnName("GRNNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool?>("IsCash");

                    b.Property<bool?>("IsDelete");

                    b.Property<int?>("IsDeletedBy");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Srndate")
                        .HasColumnName("SRNDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("SupplierId")
                        .HasColumnName("SupplierID");

                    b.Property<DateTime?>("SupplierInvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SupplierInvoiceNo")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("Srnno")
                        .HasName("PK_SRNHeader");

                    b.ToTable("Tbl_ProductSRNHeader");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblRptTempProductSaleIncomeMonthBase", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AprilCount")
                        .HasColumnName("April_Count");

                    b.Property<decimal?>("AprilIncome")
                        .HasColumnName("April_Income")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("FebruaryCount")
                        .HasColumnName("February_Count");

                    b.Property<decimal?>("FebruaryIncome")
                        .HasColumnName("February_Income")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ItemId")
                        .HasColumnName("ItemID")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("ItemName")
                        .HasMaxLength(350)
                        .IsUnicode(false);

                    b.Property<int?>("JanuaryCount")
                        .HasColumnName("January_Count");

                    b.Property<decimal?>("JanuaryIncome")
                        .HasColumnName("January_Income")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("JulyCount")
                        .HasColumnName("July_Count");

                    b.Property<decimal?>("JulyIncome")
                        .HasColumnName("July_Income")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("JuneCount")
                        .HasColumnName("June_Count");

                    b.Property<decimal?>("JuneIncome")
                        .HasColumnName("June_Income")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("MarchCount")
                        .HasColumnName("March_Count");

                    b.Property<decimal?>("MarchIncome")
                        .HasColumnName("March_Income")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("MayCount")
                        .HasColumnName("May_Count");

                    b.Property<decimal?>("MayIncome")
                        .HasColumnName("May_Income")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("AutoId")
                        .HasName("PK__Tbl_Rpt___6B2329055935D4F4");

                    b.ToTable("Tbl_Rpt_Temp_ProductSaleIncomeMonthBase");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblSystemAutoNo", b =>
                {
                    b.Property<string>("FormType")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("AutoNum");

                    b.Property<bool?>("IsDateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsEveningUpdated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsMorningUpdated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("LastModifiedTime");

                    b.HasKey("FormType")
                        .HasName("PK_SystemAutoNo");

                    b.ToTable("Tbl_SystemAutoNo");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TreatmentType", b =>
                {
                    b.Property<int>("Ttid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TTId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<string>("ColorCode");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId");

                    b.Property<int>("Duration");

                    b.Property<int>("EnteredBy");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Ttname")
                        .IsRequired()
                        .HasColumnName("TTName")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.HasKey("Ttid")
                        .HasName("PK_Tbl_Master_TreatmentType");

                    b.HasIndex("BranchId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tbl_Mast_TreatmentType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("BranchId");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Designation")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool?>("IsActive");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("IsPasswordChanged");

                    b.Property<string>("MobNo")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PasswordChangedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Token");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("UserName");

                    b.ToTable("Tbl_User");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.Branch", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblCompany", "Company")
                        .WithMany("TblBranch")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Tbl_Branch_Tbl_Company");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.Customer", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Branch", "Branch")
                        .WithMany("Customers")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_Tbl_Customer_Tbl_Branch");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerGiftVoucher", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Customer", "Customer")
                        .WithMany("CustomerGiftVouchers")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Tbl_CustomerGiftVoucher_Tbl_Customer");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Department", "Department")
                        .WithMany("TblCustomerGiftVoucher")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Tbl_CustomerGiftVoucher_Tbl_Mast_Department");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.PaymentType", "Pt")
                        .WithMany("TblCustomerGiftVoucher")
                        .HasForeignKey("Ptid")
                        .HasConstraintName("FK_Tbl_CustomerGiftVoucher_Tbl_Mast_PaymentType");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TreatmentType", "Tt")
                        .WithMany("TblCustomerGiftVoucher")
                        .HasForeignKey("Ttid")
                        .HasConstraintName("FK_Tbl_CustomerGiftVoucher_Tbl_Mast_TreatmentType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerInvoiceHeader", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.CreditCardType", "CreditCardType")
                        .WithMany()
                        .HasForeignKey("CCTId");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.CustomerScheduleTreatment")
                        .WithMany("TblCustomerInvoiceHeader")
                        .HasForeignKey("CustomerScheduleTreatmentCstid");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Department", "Department")
                        .WithMany("TblCustomerInvoiceHeader")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Tbl_CustomerInvoiceHeader_Tbl_Mast_Department");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.PaymentType", "Pt")
                        .WithMany("TblCustomerInvoiceHeader")
                        .HasForeignKey("Ptid")
                        .HasConstraintName("FK_Tbl_CustomerInvoiceHeader_Tbl_Mast_PaymentType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerInvoiceProducts", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "EmpnoNavigation")
                        .WithMany()
                        .HasForeignKey("Empno")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.CustomerInvoiceHeader", "InvoiceNoNavigation")
                        .WithMany("CustomerInvoiceProducts")
                        .HasForeignKey("InvoiceNo")
                        .HasConstraintName("FK_Tbl_CustomerInvoiceProducts_Tbl_CustomerInvoiceHeader");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Product", "ProductNavigation")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerInvoiceTreatment", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.CustomerScheduleTreatment", "Cst")
                        .WithMany()
                        .HasForeignKey("Cstid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "EmpnoNavigation")
                        .WithMany("TblCustomerInvoiceTreatment")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_Tbl_CustomerInvoiceTreatment_Tbl_EmployeeDetail");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.CustomerInvoiceHeader", "InvoiceNoNavigation")
                        .WithMany("CustomerInvoiceTreatments")
                        .HasForeignKey("InvoiceNo")
                        .HasConstraintName("FK_Tbl_CustomerInvoiceTreatment_Tbl_CustomerInvoiceHeader");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TreatmentType", "Tt")
                        .WithMany("TblCustomerInvoiceTreatment")
                        .HasForeignKey("Ttid")
                        .HasConstraintName("FK_Tbl_CustomerInvoiceTreatment_Tbl_Mast_TreatmentType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerSchedule", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Customer", "Customer")
                        .WithMany("CustomerSchedules")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Tbl_CustomerSchedule_Tbl_Customer");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Department", "Department")
                        .WithMany("TblCustomerSchedule")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Tbl_CustomerSchedule_Tbl_Mast_Department");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.CustomerScheduleTreatment", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.CustomerSchedule", "CustomerSchedule")
                        .WithMany("CustomerScheduleTreatments")
                        .HasForeignKey("Csid")
                        .HasConstraintName("FK_Tbl_CustomerScheduleTreatment_Tbl_CustomerSchedule");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "Employee")
                        .WithMany("TblCustomerScheduleTreatment")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_Tbl_CustomerScheduleTreatment_Tbl_EmployeeDetail");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TreatmentType", "Tt")
                        .WithMany("TblCustomerScheduleTreatment")
                        .HasForeignKey("Ttid")
                        .HasConstraintName("FK_Tbl_CustomerScheduleTreatment_Tbl_Mast_TreatmentType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.Department", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Branch", "Branch")
                        .WithMany("Departments")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_Tbl_Mast_Department_Tbl_Branch");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblMastBank", "Bank")
                        .WithMany("TblEmployeeDetail")
                        .HasForeignKey("BankId")
                        .HasConstraintName("FK_Tbl_EmployeeDetail_Tbl_Mast_Bank");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblMastOriginCountry", "Country")
                        .WithMany("TblEmployeeDetail")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Tbl_EmployeeDetail_Tbl_Mast_OriginCountry");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Department", "Department")
                        .WithMany("EmployeeDetail")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Tbl_EmployeeDetail_Tbl_Mast_Department");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblMastDesignation", "Designation")
                        .WithMany("TblEmployeeDetail")
                        .HasForeignKey("DesignationId")
                        .HasConstraintName("FK_Tbl_EmployeeDetail_Tbl_Mast_Designation");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblMastNationality", "Nationality")
                        .WithMany("TblEmployeeDetail")
                        .HasForeignKey("NationalityId")
                        .HasConstraintName("FK_Tbl_EmployeeDetail_Tbl_Mast_Nationality");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.EmployeeRoster", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "EmpnoNavigation")
                        .WithMany("EmployeeRosters")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_Tbl_RosterDetail_Tbl_EmployeeDetail");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.Product", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.ProductSellingPrice", "ProductSellingPrice")
                        .WithMany()
                        .HasForeignKey("ProductSellingPriceItemId");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeAllowances", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblMastAllowances", "Allowance")
                        .WithMany("TblEmployeeAllowances")
                        .HasForeignKey("AllowanceId")
                        .HasConstraintName("FK_Tbl_EmployeeAllowances_Tbl_Mast_Allowances1");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "EmpnoNavigation")
                        .WithMany("TblEmployeeAllowances")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_Tbl_EmployeeAllowances_Tbl_EmployeeDetail1");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeBasicSalary", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "EmpnoNavigation")
                        .WithMany("TblEmployeeBasicSalary")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_Tbl_EmployeeBasicSalary_Tbl_EmployeeDetail");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeCommision", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblMastCommission", "Commission")
                        .WithMany("TblEmployeeCommision")
                        .HasForeignKey("CommissionId")
                        .HasConstraintName("FK_Tbl_EmployeeCommision_Tbl_Mast_Commission1");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "EmpnoNavigation")
                        .WithMany("TblEmployeeCommision")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_Tbl_EmployeeCommision_Tbl_EmployeeDetail1");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeDeduction", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblMastDeduction", "Deduction")
                        .WithMany("TblEmployeeDeduction")
                        .HasForeignKey("DeductionId")
                        .HasConstraintName("FK_Tbl_EmployeeDeduction_Tbl_Mast_Deduction1");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "EmpnoNavigation")
                        .WithMany("TblEmployeeDeduction")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_Tbl_EmployeeDeduction_Tbl_EmployeeDetail1");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblEmployeeLeave", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.EmployeeDetail", "EmpnoNavigation")
                        .WithMany("TblEmployeeLeave")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_Tbl_EmployeeLeave_Tbl_EmployeeDetail");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.TblMastLeaveType", "LeaveType")
                        .WithMany("TblEmployeeLeave")
                        .HasForeignKey("LeaveTypeId")
                        .HasConstraintName("FK_Tbl_EmployeeLeave_Tbl_Mast_LeaveType");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TblMastDesignation", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Branch", "Branch")
                        .WithMany("Designations")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_Tbl_Mast_Designation_Tbl_Branch");
                });

            modelBuilder.Entity("BeautyPro.CRM.EF.DomainModel.TreatmentType", b =>
                {
                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Branch", "Branch")
                        .WithMany("TreatmentTypes")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_Tbl_Mast_TreatmentType_Tbl_Branch");

                    b.HasOne("BeautyPro.CRM.EF.DomainModel.Department", "Department")
                        .WithMany("TreatmentTypes")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Tbl_Mast_TreatmentType_Tbl_Mast_Department");
                });
#pragma warning restore 612, 618
        }
    }
}
